project:
  type: website
  output-dir: _site
  render:
    - index.qmd

website:
  title: "State and Local Government Finance Research Lab"
  site-url: "https://gchen3.github.io/slgf_lab/"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true

editor: visual

