project:
  type: website
  output-dir: _site

website:
  title: "State and Local Government Finance Research Lab"
  site-url: "https://github.com/gchen3/slgf_lab" #https://slgfrl.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

