project:
  type: website
  output-dir: _site

website:
  title: "State and Local Government Finance Research Lab"
  site-url: "https://gchen3.github.io/slgf_lab/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - index_quarto.qmd

format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true

editor: visual

